### ISSUE TITLE
Text is not center aligned

### ISSUE THREAD

**Issue by TartejBrothers** [AirTechWick/PortfolioWebsite#5]
# Issues
- The section `What I do` doesn't have equal div widths and makes the whole section bit off center.
![image](https://github.com/AirTechWick/PortfolioWebsite/assets/112921727/a7cb8540-f285-4c5b-a35f-9545afdbcb85)
- This can be fixed by making all the three sections of the equal width.

**Comment by AirTechWick** [comment]
Thank you will make this change
